name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Tests
        run: cargo test --all-targets
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
